//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Cache {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Cache.ICacheJCDecaux")]
    public interface ICacheJCDecaux {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheJCDecaux/getContracts", ReplyAction="http://tempuri.org/ICacheJCDecaux/getContractsResponse")]
        string getContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheJCDecaux/getContracts", ReplyAction="http://tempuri.org/ICacheJCDecaux/getContractsResponse")]
        System.Threading.Tasks.Task<string> getContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheJCDecaux/getAllStationsOfContract", ReplyAction="http://tempuri.org/ICacheJCDecaux/getAllStationsOfContractResponse")]
        string getAllStationsOfContract(string contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheJCDecaux/getAllStationsOfContract", ReplyAction="http://tempuri.org/ICacheJCDecaux/getAllStationsOfContractResponse")]
        System.Threading.Tasks.Task<string> getAllStationsOfContractAsync(string contract);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICacheJCDecauxChannel : Project1.Cache.ICacheJCDecaux, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CacheJCDecauxClient : System.ServiceModel.ClientBase<Project1.Cache.ICacheJCDecaux>, Project1.Cache.ICacheJCDecaux {
        
        public CacheJCDecauxClient() {
        }
        
        public CacheJCDecauxClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CacheJCDecauxClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CacheJCDecauxClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CacheJCDecauxClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getContracts() {
            return base.Channel.getContracts();
        }
        
        public System.Threading.Tasks.Task<string> getContractsAsync() {
            return base.Channel.getContractsAsync();
        }
        
        public string getAllStationsOfContract(string contract) {
            return base.Channel.getAllStationsOfContract(contract);
        }
        
        public System.Threading.Tasks.Task<string> getAllStationsOfContractAsync(string contract) {
            return base.Channel.getAllStationsOfContractAsync(contract);
        }
    }
}
