//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSoap.BikingRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BikingRef.IMyBiking")]
    public interface IMyBiking {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBiking/getTrajectory", ReplyAction="http://tempuri.org/IMyBiking/getTrajectoryResponse")]
        string[] getTrajectory(string fromAdress, string toAdress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyBiking/getTrajectory", ReplyAction="http://tempuri.org/IMyBiking/getTrajectoryResponse")]
        System.Threading.Tasks.Task<string[]> getTrajectoryAsync(string fromAdress, string toAdress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyBikingChannel : ClientSoap.BikingRef.IMyBiking, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyBikingClient : System.ServiceModel.ClientBase<ClientSoap.BikingRef.IMyBiking>, ClientSoap.BikingRef.IMyBiking {
        
        public MyBikingClient() {
        }
        
        public MyBikingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyBikingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyBikingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyBikingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getTrajectory(string fromAdress, string toAdress) {
            return base.Channel.getTrajectory(fromAdress, toAdress);
        }
        
        public System.Threading.Tasks.Task<string[]> getTrajectoryAsync(string fromAdress, string toAdress) {
            return base.Channel.getTrajectoryAsync(fromAdress, toAdress);
        }
    }
}
